// <auto-generated />
namespace CreativeCollab_yj_sy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Journeysusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Journeysusers));
        
        string IMigrationMetadata.Id
        {
            get { return "202404050125011_Journeys-users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
